[[RadeonProRender]]
arch = "aarch64"
git-tree-sha1 = "a85dba255003be993ab498ab7414b795af11ce27"
os = "macos"

    [[RadeonProRender.download]]
    sha256 = "78d6407ba167eb78249eff72d9f3d9a471fe1b4f7c59acc8ff05c03d2145bcc3"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v3.1.0+0/RadeonProRender.v3.1.0.aarch64-apple-darwin.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
git-tree-sha1 = "a85dba255003be993ab498ab7414b795af11ce27"
os = "macos"

    [[RadeonProRender.download]]
    sha256 = "78d6407ba167eb78249eff72d9f3d9a471fe1b4f7c59acc8ff05c03d2145bcc3"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v3.1.0+0/RadeonProRender.v3.1.0.x86_64-apple-darwin.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23b13b39f239b344d4ddd2932c0eed8790aacf4c"
libc = "glibc"
os = "linux"

    [[RadeonProRender.download]]
    sha256 = "66112c87a218ea1d285015c8134f34cbcc1050d66bdf71aff3fd1fd41c11d33e"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v3.1.0+0/RadeonProRender.v3.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23b13b39f239b344d4ddd2932c0eed8790aacf4c"
libc = "glibc"
os = "linux"

    [[RadeonProRender.download]]
    sha256 = "66112c87a218ea1d285015c8134f34cbcc1050d66bdf71aff3fd1fd41c11d33e"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v3.1.0+0/RadeonProRender.v3.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7213e960452537ff62e1c812771222584a7fa4c6"
os = "windows"

    [[RadeonProRender.download]]
    sha256 = "63694e7f77878fdd04873eaf315a2ec01ef716703541b50cccd2b92968dcce5a"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v3.1.0+0/RadeonProRender.v3.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7213e960452537ff62e1c812771222584a7fa4c6"
os = "windows"

    [[RadeonProRender.download]]
    sha256 = "63694e7f77878fdd04873eaf315a2ec01ef716703541b50cccd2b92968dcce5a"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v3.1.0+0/RadeonProRender.v3.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
