[[RadeonProRender]]
arch = "aarch64"
git-tree-sha1 = "4d0551cd370afc38b98b4e8e8acec2939a9def8e"
os = "macos"

    [[RadeonProRender.download]]
    sha256 = "e02dba8c98a9dbe60ad9cdee237a85533a8c33c867ba03b2e0f046cf478ecf0f"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v3.1.5+0/RadeonProRender.v3.1.5.aarch64-apple-darwin.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
git-tree-sha1 = "4d0551cd370afc38b98b4e8e8acec2939a9def8e"
os = "macos"

    [[RadeonProRender.download]]
    sha256 = "e02dba8c98a9dbe60ad9cdee237a85533a8c33c867ba03b2e0f046cf478ecf0f"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v3.1.5+0/RadeonProRender.v3.1.5.x86_64-apple-darwin.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e47b64dfdc46107d69ce5e313f96fb0376d9866f"
libc = "glibc"
os = "linux"

    [[RadeonProRender.download]]
    sha256 = "a6c4a46afa8b3ca5a3afa91f1f10b13e0416d3a2d0b3a7076138c93b7886b7be"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v3.1.5+0/RadeonProRender.v3.1.5.x86_64-linux-gnu-cxx03.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e47b64dfdc46107d69ce5e313f96fb0376d9866f"
libc = "glibc"
os = "linux"

    [[RadeonProRender.download]]
    sha256 = "a6c4a46afa8b3ca5a3afa91f1f10b13e0416d3a2d0b3a7076138c93b7886b7be"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v3.1.5+0/RadeonProRender.v3.1.5.x86_64-linux-gnu-cxx11.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38a3c9dae883bb4c0994134f708e34764312ccfd"
os = "windows"

    [[RadeonProRender.download]]
    sha256 = "6e5ce235918edda40d184cf4c06262af7921489f8f21e98651527ba3a6c01fb8"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v3.1.5+0/RadeonProRender.v3.1.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38a3c9dae883bb4c0994134f708e34764312ccfd"
os = "windows"

    [[RadeonProRender.download]]
    sha256 = "6e5ce235918edda40d184cf4c06262af7921489f8f21e98651527ba3a6c01fb8"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v3.1.5+0/RadeonProRender.v3.1.5.x86_64-w64-mingw32-cxx11.tar.gz"
