[[RadeonProRender]]
arch = "x86_64"
git-tree-sha1 = "fe0392a1c5113dbd5f2e613c9385f5165206cf73"
os = "macos"

    [[RadeonProRender.download]]
    sha256 = "09c1c7e4d7e8b73afa722e8c7f59cf912b0c60acd52d6a88ca9f5621a56cbe4c"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v2.2.9+0/RadeonProRender.v2.2.9.x86_64-apple-darwin.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dff5f45d6d0845a226696f5d3f94b0c916820afd"
libc = "glibc"
os = "linux"

    [[RadeonProRender.download]]
    sha256 = "edcfa59f329d583b7c09cef5875c6c9bf2d3b041984200acfd2c73beb87877fa"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v2.2.9+0/RadeonProRender.v2.2.9.x86_64-linux-gnu-cxx03.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c548d0d933036e6330067ddf4746912387428467"
libc = "glibc"
os = "linux"

    [[RadeonProRender.download]]
    sha256 = "615f5624ce754af65966ebc983e6b38b83634316c92b1b86cee00530a93d289d"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v2.2.9+0/RadeonProRender.v2.2.9.x86_64-linux-gnu-cxx11.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8d7229ad05efb83ecdf208f08543158d34c1f5b"
os = "windows"

    [[RadeonProRender.download]]
    sha256 = "44f74af892522c679853087cb668dd703d5d705c9d8a68b88286c5adfb5dabc8"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v2.2.9+0/RadeonProRender.v2.2.9.x86_64-w64-mingw32-cxx03.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48116dfaa680f625e8f65ca03cf4abc97267761d"
os = "windows"

    [[RadeonProRender.download]]
    sha256 = "2fabfc99a3045af8749a1e1439f90f8cf5546aac85fed716a06443cc2f01ab48"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v2.2.9+0/RadeonProRender.v2.2.9.x86_64-w64-mingw32-cxx11.tar.gz"
