[[RadeonProRender]]
arch = "aarch64"
git-tree-sha1 = "b92cab50f632b77cac59e3863c9f522f7fe523eb"
os = "macos"

    [[RadeonProRender.download]]
    sha256 = "d79f6ca88b9aef2ea66c03cc62c7f0e63fae5b41b1189a10a345f88acdaadc59"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v2.2.12+0/RadeonProRender.v2.2.12.aarch64-apple-darwin.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
git-tree-sha1 = "b53c5454a389ef33807fc830c3d6bac392f65ce0"
os = "macos"

    [[RadeonProRender.download]]
    sha256 = "c7911c5f8e9cfe9044812225f0fd49609e76ec35149ee069be3a1374c15a10a3"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v2.2.12+0/RadeonProRender.v2.2.12.x86_64-apple-darwin.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8deae97c7195f3113e97b1b107284ec3a59d581c"
libc = "glibc"
os = "linux"

    [[RadeonProRender.download]]
    sha256 = "9127a7c5d6be3ea236d4025c73cd68e522fbe51fcf0e0e2608fc5388b435735a"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v2.2.12+0/RadeonProRender.v2.2.12.x86_64-linux-gnu-cxx03.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edd1188321f607477f0cc2edb2e850abd432e8cb"
libc = "glibc"
os = "linux"

    [[RadeonProRender.download]]
    sha256 = "e457681a2313c639574056ef93767818d553c8cd44340741de8bbd2ace52e5c7"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v2.2.12+0/RadeonProRender.v2.2.12.x86_64-linux-gnu-cxx11.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "edae88f2c24bb4feb62a43cad36d8abf01f3b27e"
os = "windows"

    [[RadeonProRender.download]]
    sha256 = "a34d35fc1e13190a41d4ff04e95e3f514091cb66dde6d43c28b60ca4aad31d34"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v2.2.12+0/RadeonProRender.v2.2.12.x86_64-w64-mingw32-cxx03.tar.gz"
[[RadeonProRender]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "432a70b747c236f91ddde41d4a8f7e159c32e67f"
os = "windows"

    [[RadeonProRender.download]]
    sha256 = "aa5837f07a57170b0212ca41d7cfedfb43e0f337d742c8725e3c8a586e047472"
    url = "https://github.com/JuliaBinaryWrappers/RadeonProRender_jll.jl/releases/download/RadeonProRender-v2.2.12+0/RadeonProRender.v2.2.12.x86_64-w64-mingw32-cxx11.tar.gz"
