# Autogenerated wrapper script for RadeonProRender_jll for aarch64-apple-darwin
export libNorthstar64, libProRenderGLTF, libRadeonProRender64, libRprLoadStore64, libTahoe64

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("RadeonProRender")
JLLWrappers.@declare_library_product(libNorthstar64, "libNorthstar64.dylib")
JLLWrappers.@declare_library_product(libProRenderGLTF, "@rpath/libProRenderGLTF.dylib")
JLLWrappers.@declare_library_product(libRadeonProRender64, "libRadeonProRender64.dylib")
JLLWrappers.@declare_library_product(libRprLoadStore64, "libRprLoadStore64.dylib")
JLLWrappers.@declare_library_product(libTahoe64, "@rpath/libTahoe64.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libNorthstar64,
        "lib/libNorthstar64.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libProRenderGLTF,
        "lib/libProRenderGLTF.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libRadeonProRender64,
        "lib/libRadeonProRender64.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libRprLoadStore64,
        "lib/libRprLoadStore64.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTahoe64,
        "lib/libTahoe64.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
