# Autogenerated wrapper script for RadeonProRender_jll for x86_64-linux-gnu-cxx11
export libNorthstar64, libProRenderGLTF, libRadeonProRender64, libRprLoadStore64, libTahoe64

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("RadeonProRender")
JLLWrappers.@declare_library_product(libNorthstar64, "libNorthstar64.so")
JLLWrappers.@declare_library_product(libProRenderGLTF, "libProRenderGLTF.so")
JLLWrappers.@declare_library_product(libRadeonProRender64, "libRadeonProRender64.so")
JLLWrappers.@declare_library_product(libRprLoadStore64, "libRprLoadStore64.so")
JLLWrappers.@declare_library_product(libTahoe64, "libTahoe64.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libNorthstar64,
        "lib/libNorthstar64.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libProRenderGLTF,
        "lib/libProRenderGLTF.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libRadeonProRender64,
        "lib/libRadeonProRender64.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libRprLoadStore64,
        "lib/libRprLoadStore64.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTahoe64,
        "lib/libTahoe64.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
